React version
mendix/SearchInput pull request #12
Opened 2019-08-29 12:46 UTC by MeisamMahdian

[WIP] React version with Dojo wrapper

2019-08-29 12:49 UTC, iannbing commented on src/containers/Wrapper.tsx
> +  componentWillReceiveProps(newProps: SearchInputProps) {
This lifecycle hook will be deprecated soon, currently it is *unsafe*. See https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

2019-08-29 12:58 UTC, iannbing commented on src/containers/Wrapper.tsx
> +    this.state = { keyword: props.keyword };
Does Mendix pass along `keyword` to this widget? I cannot find it in `widget.config.ejs`.

2019-08-29 13:05 UTC, iannbing commented on src/containers/Container.tsx
> +    this.setState({ progressId: this.showProgress() }, () => {
The way you use `this.setState` is not fully following the React docs. Check it out here https://reactjs.org/docs/react-component.html#setstate

2019-08-29 13:11 UTC, iannbing commented on src/typings/SearchInputProps.ts
> +import { Widget } from '../typings';
all the files in `typings` folder should follow the convention `foo.d.ts`, to show that it's only provide types.

2019-08-29 13:11 UTC, iannbing commented on src/typings/Widget.ts
> +export interface Widget {
all the files in `typings` folder should follow the convention `foo.d.ts`, to show that it's only provide types.

2019-08-29 13:12 UTC, iannbing commented on src/containers/Container.tsx
> +      progressId = mx.ui.showProgress(progressBarMessage, isModal);
could you also move this `mx.ui` implementation to `mxHelper.tsx`?

2019-08-29 13:15 UTC, iannbing commented on src/components/SearchInputComponent.tsx
> +  let btnClass = 'btn';
The string-concatenation is not so readable here.

2019-08-29 13:16 UTC, iannbing commented on src/components/SearchInputComponent.tsx
> +  tabindex,
camelcase here?

2019-08-29 13:16 UTC, iannbing commented on src/components/SearchInputComponent.tsx
> +  buttonstyle,
camelcase here?

2019-08-29 13:18 UTC, iannbing commented on src/containers/Container.tsx
> +    this.setState({ progressId: this.showProgress() }, () => {
The name of this function can be more descriptive? `run` is too generic IMO.

2019-08-29 13:23 UTC, iannbing commented on src/containers/Container.tsx
> +      tabindex,
How did `Container` get `tabindex`? `Wrapper` didn't provide this prop.

2019-08-29 13:24 UTC, MeisamMahdian commented on src/containers/Wrapper.tsx
> +    this.state = { keyword: props.keyword };
When the data source changes outside of the widget a callback will fire to pass it to the component.

2019-08-29 13:28 UTC, iannbing commented on src/containers/Container.tsx
> +    mxObject.set(targetAttribute!, keyword);
is this exclamation mark on purpose?

2019-08-29 13:28 UTC, iannbing commented on src/index.tsx
> +            self.params.targetAttribute!,
is this exclamation mark on purpose?

2019-08-29 13:30 UTC, MeisamMahdian commented on src/containers/Container.tsx
> +    this.setState({ progressId: this.showProgress() }, () => {
Please make your point more clear.

2019-08-29 13:38 UTC, iannbing commented on src/containers/Wrapper.tsx
> +import '../style/style.scss';
I find it a bit awkward to import css on top of the file. Could you put it after all the other imports?

2019-08-29 13:39 UTC, iannbing commented on src/containers/Wrapper.tsx
> +import React from 'react';
Usually node_modules imports are put on top, and then file imports. Mixing the order is not that readable.

2019-08-29 13:47 UTC, iannbing commented on src/index.tsx
> +import _widgetBase from 'MxWidgetBase';
You can declare `MxWidgetBase` and `dojoBaseDecalre` as modules to avoid warnings.

2019-08-29 13:49 UTC, iannbing commented on src/components/SearchInputComponent.tsx
> +    <div className="input-group">
This className is not used in the `scss` files.

2019-08-29 13:50 UTC, iannbing commented on src/components/SearchInputComponent.tsx
> +      <span className="input-group-btn searchInputButton">
This className is not used in the `scss` files

2019-08-29 13:56 UTC, iannbing commented on src/style/_searchInput.scss
> +.searchInput {
I cannot find the usage of this class `searchInput`.

2019-08-29 13:57 UTC, iannbing commented on src/style/_searchInput.scss
> +    top: 0px !important;
Does stylelint work on your machine? You should see a warning on `0px`. Just put it `0`. `px` is not necessary.

2019-08-29 13:59 UTC, iannbing commented on src/__tests__/SearchInput.test.tsx
> +import React from 'react';
'__tests__' folder should be in the same folder with the tested file. So, I think this test should be moved to `components` folder.

2019-08-29 14:08 UTC, iannbing commented on .gitlab-ci.yml
> +    - npm run install
`npm run install` is not a valid command (I know it's from Osama's version). Anyway, this file is useless because it's a github repo, not gitlab. We can set up CI/CD using CircleCI or TravisCI though.

2019-08-29 14:12 UTC, iannbing commented on src/index.tsx
> +import _widgetBase from 'MxWidgetBase';
Create a file something like `mendix.d.ts` in the `typings` folder, and add this into `tsconfig.js`
```
"include": [
    "typings/**/*",
     ...
]
```
Then typescript will not complain anymore.

2019-08-29 14:19 UTC, iannbing requested changes
Good job! 👍 Looks very nice! Thanks for integrating hyper pattern! 

I think I understand the reason why you separate `Wrapper` and `Container`. `Wrapper` is responsible to handle updates from Modeler, and `Container` handles the React part. However, the naming of these two components are not telling me the intention, but I don't have a better idea 😅

2019-08-30 07:58 UTC, MeisamMahdian commented on src/components/SearchInputComponent.tsx
> +  tabindex,
These properties are from widget settings and I didn't changed them for backward compatibility.

2019-08-30 07:58 UTC, MeisamMahdian commented on src/components/SearchInputComponent.tsx
> +  buttonstyle,
These properties are from widget settings and I didn't changed them for backward compatibility.

2019-08-30 07:58 UTC, MeisamMahdian commented on src/containers/Container.tsx
> +      tabindex,
Fixed

2019-08-30 07:59 UTC, MeisamMahdian commented on src/containers/Container.tsx
> +    mxObject.set(targetAttribute!, keyword);
Remained from previous props structure.
Fixed.

2019-08-30 08:00 UTC, MeisamMahdian commented on src/index.tsx
> +            self.params.targetAttribute!,
Remained from previous props structure.
Fixed.

2019-08-30 08:02 UTC, MeisamMahdian commented on src/index.tsx
> +import _widgetBase from 'MxWidgetBase';
Fixed

2019-08-30 08:03 UTC, MeisamMahdian commented on src/components/SearchInputComponent.tsx
> +      <span className="input-group-btn searchInputButton">
Fixed.

2019-08-30 08:03 UTC, MeisamMahdian commented on src/style/_searchInput.scss
> +.searchInput {
Fixed.

2019-08-30 08:03 UTC, MeisamMahdian commented on src/__tests__/SearchInput.test.tsx
> +import React from 'react';
Fixed.

2019-08-30 08:03 UTC, MeisamMahdian commented on .gitlab-ci.yml
> +    - npm run install
Fixed.

2019-08-30 09:00 UTC, MeisamMahdian commented on src/components/SearchInputComponent.tsx
> +    <div className="input-group">
Fixed

2019-08-30 09:01 UTC, MeisamMahdian commented on src/style/_searchInput.scss
> +    top: 0px !important;
No but Fixed

2019-08-30 09:27 UTC, iannbing commented on src/components/SearchInputComponent.tsx
> +  buttonstyle,
I'm not sure what you mean about backward compatibility. User doesn't see this naming from Studio Pro, and you will release a new version anyway. There's no dependencies on this property.

2019-09-02 09:44 UTC, MeisamMahdian commented on src/containers/Container.tsx
> +    this.setState({ progressId: this.showProgress() }, () => {
I changed it to function component

2019-09-02 10:29 UTC, MeisamMahdian commented on src/containers/Wrapper.tsx
> +  componentWillReceiveProps(newProps: SearchInputProps) {
I eliminated the wrapper and made it fully controlled

2019-09-02 10:29 UTC, MeisamMahdian commented on src/components/SearchInputComponent.tsx
> +  let btnClass = 'btn';
Changed it

2019-09-02 15:04 UTC, iannbing approved these changes
Looks nice!

2019-09-02 15:15 UTC, merged